"""empty message

Revision ID: 50b90a335eb5
Revises: c28aa644637c
Create Date: 2020-05-30 01:35:30.386625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b90a335eb5'
down_revision = 'c28aa644637c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('member_assoc',
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['userprofile.id'], ),
    sa.ForeignKeyConstraint(['organization'], ['organization.id'], )
    )
    op.create_table('moderator_assoc',
    sa.Column('moderator', sa.Integer(), nullable=True),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moderator'], ['userprofile.id'], ),
    sa.ForeignKeyConstraint(['organization'], ['organization.id'], )
    )
    op.create_table('org_assoc',
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.Column('article', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article'], ['article.id'], ),
    sa.ForeignKeyConstraint(['organization'], ['organization.id'], )
    )
    op.add_column('article', sa.Column('needsReview', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('githubLink', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linkedinLink', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('occupation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('twitterLink', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('isPublished', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('article', 'needsReview')
    op.drop_table('org_assoc')
    op.drop_table('moderator_assoc')
    op.drop_table('member_assoc')
    op.drop_table('organization')
    # ### end Alembic commands ###
