"""empty message

Revision ID: 55b82bb0eb01
Revises: c4f9a7692f30
Create Date: 2020-05-26 22:37:51.111491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b82bb0eb01'
down_revision = 'c4f9a7692f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'modSetting',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'modSetting',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
