"""empty message

Revision ID: c4f9a7692f30
Revises: bb10324d2013
Create Date: 2020-05-26 21:08:53.217962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f9a7692f30'
down_revision = 'bb10324d2013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('needsReview', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'needsReview')
    # ### end Alembic commands ###
